CREATE TYPE public.event_type AS ENUM ('Dota', 'CS', 'MLBB', 'HoK', 'Others');

CREATE TABLE public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name TEXT NOT NULL,
  time BIGINT NOT NULL,
  type public.event_type NOT NULL,
  gardener BIGINT NOT NULL,
  hours SMALLINT NOT NULL,
  CONSTRAINT events_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;
