// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type CsScoreboard struct {
	ID    int64
	Score int64
}

type DotaScoreboard struct {
	ID    int64
	Score int64
}

type Event struct {
	ID       int64
	Name     string
	Time     int64
	Type     string
	Gardener int64
	Hours    int64
}

type HokScoreboard struct {
	ID    int64
	Score int64
}

type MlbbScoreboard struct {
	ID    int64
	Score int64
}
