// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (name, time, type, gardener, hours) VALUES (?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	Name     string
	Time     int64
	Type     string
	Gardener int64
	Hours    int64
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.Name,
		arg.Time,
		arg.Type,
		arg.Gardener,
		arg.Hours,
	)
	return err
}
