// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package sqlc

import (
	"context"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (name, time, type, gardener, hours) VALUES (?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	Name     string
	Time     int64
	Type     string
	Gardener int64
	Hours    int64
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.Name,
		arg.Time,
		arg.Type,
		arg.Gardener,
		arg.Hours,
	)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE name = ? AND time = ?
`

type DeleteEventParams struct {
	Name string
	Time int64
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, arg.Name, arg.Time)
	return err
}

const getEventsForGame = `-- name: GetEventsForGame :many
SELECT
    id, name, time, type, gardener, hours
FROM
    events
WHERE time BETWEEN ? AND ?
AND type = ?
`

type GetEventsForGameParams struct {
	Start int64
	End   int64
	Type  string
}

func (q *Queries) GetEventsForGame(ctx context.Context, arg GetEventsForGameParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventsForGame, arg.Start, arg.End, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Time,
			&i.Type,
			&i.Gardener,
			&i.Hours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsForGardener = `-- name: GetEventsForGardener :many
SELECT
    id, name, time, type, gardener, hours
FROM
    events
WHERE time BETWEEN ? AND ?
AND gardener = ?
`

type GetEventsForGardenerParams struct {
	Start    int64
	End      int64
	Gardener int64
}

func (q *Queries) GetEventsForGardener(ctx context.Context, arg GetEventsForGardenerParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventsForGardener, arg.Start, arg.End, arg.Gardener)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Time,
			&i.Type,
			&i.Gardener,
			&i.Hours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
