// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package sqlc

import (
	"context"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (name, time, type, gardener, hours) VALUES ($1, $2, $3, $4, $5)
`

type CreateEventParams struct {
	Name     string
	Time     int64
	Type     EventType
	Gardener int64
	Hours    int16
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.Name,
		arg.Time,
		arg.Type,
		arg.Gardener,
		arg.Hours,
	)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE name = $1 AND time = $2 AND type = $3 AND hours = $4
`

type DeleteEventParams struct {
	Name  string
	Time  int64
	Type  EventType
	Hours int16
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) error {
	_, err := q.db.Exec(ctx, deleteEvent,
		arg.Name,
		arg.Time,
		arg.Type,
		arg.Hours,
	)
	return err
}

const getEventsForGame = `-- name: GetEventsForGame :many
SELECT
    id, name, time, type, gardener, hours
FROM
    events
WHERE time BETWEEN $1 AND $2
AND type = $3
`

type GetEventsForGameParams struct {
	Time   int64
	Time_2 int64
	Type   EventType
}

func (q *Queries) GetEventsForGame(ctx context.Context, arg GetEventsForGameParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsForGame, arg.Time, arg.Time_2, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Time,
			&i.Type,
			&i.Gardener,
			&i.Hours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsForGardener = `-- name: GetEventsForGardener :many
SELECT
    id, name, time, type, gardener, hours
FROM
    events
WHERE time BETWEEN $1 AND $2
AND gardener = $3
`

type GetEventsForGardenerParams struct {
	Time     int64
	Time_2   int64
	Gardener int64
}

func (q *Queries) GetEventsForGardener(ctx context.Context, arg GetEventsForGardenerParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsForGardener, arg.Time, arg.Time_2, arg.Gardener)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Time,
			&i.Type,
			&i.Gardener,
			&i.Hours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
