// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Event struct {
	ID       int64
	Name     string
	Time     int64
	Type     string
	Gardener int64
	Hours    int64
}

type Scoreboard struct {
	Member int64
	Score  int64
	Game   string
}
