// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scoreboard.sql

package sqlc

import (
	"context"
)

const clearScoreboardForGame = `-- name: ClearScoreboardForGame :execrows
DELETE FROM
    scoreboards
WHERE
    game = ?
`

func (q *Queries) ClearScoreboardForGame(ctx context.Context, game string) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearScoreboardForGame, game)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMemberScoreForGame = `-- name: GetMemberScoreForGame :one
SELECT
    position, score
FROM (
    SELECT
        DENSE_RANK() OVER (
            ORDER BY
                score DESC
        ) position,
        score
    FROM
        scoreboards
    WHERE
        game = ?
)
WHERE
    id = ?
`

type GetMemberScoreForGameParams struct {
	Game string
	ID   int64
}

type GetMemberScoreForGameRow struct {
	Position interface{}
	Score    int64
}

func (q *Queries) GetMemberScoreForGame(ctx context.Context, arg GetMemberScoreForGameParams) (GetMemberScoreForGameRow, error) {
	row := q.db.QueryRowContext(ctx, getMemberScoreForGame, arg.Game, arg.ID)
	var i GetMemberScoreForGameRow
	err := row.Scan(&i.Position, &i.Score)
	return i, err
}

const getWinnerForGame = `-- name: GetWinnerForGame :many
SELECT
    position, id, score
FROM (
    SELECT
        DENSE_RANK() OVER (
            ORDER BY
                score DESC
        ) position,
        id,
        score
    FROM
        scoreboards
    WHERE
        game = ?
)
WHERE
    position = 1
`

type GetWinnerForGameRow struct {
	Position interface{}
	ID       int64
	Score    int64
}

func (q *Queries) GetWinnerForGame(ctx context.Context, game string) ([]GetWinnerForGameRow, error) {
	rows, err := q.db.QueryContext(ctx, getWinnerForGame, game)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWinnerForGameRow
	for rows.Next() {
		var i GetWinnerForGameRow
		if err := rows.Scan(&i.Position, &i.ID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const showScoreboardForGame = `-- name: ShowScoreboardForGame :many
SELECT
    DENSE_RANK() OVER (
        ORDER BY
            score DESC
    ) position,
    id,
    score
FROM
    scoreboards
WHERE
    game = ?
`

type ShowScoreboardForGameRow struct {
	Position interface{}
	ID       int64
	Score    int64
}

func (q *Queries) ShowScoreboardForGame(ctx context.Context, game string) ([]ShowScoreboardForGameRow, error) {
	rows, err := q.db.QueryContext(ctx, showScoreboardForGame, game)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShowScoreboardForGameRow
	for rows.Next() {
		var i ShowScoreboardForGameRow
		if err := rows.Scan(&i.Position, &i.ID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScoreboardForGame = `-- name: UpdateScoreboardForGame :execrows
INSERT INTO
    scoreboards (member, score, game)
VALUES
    (?, ?, ?) ON CONFLICT (member) DO
UPDATE
SET
    score = score + 1
`

type UpdateScoreboardForGameParams struct {
	Member int64
	Score  int64
	Game   string
}

func (q *Queries) UpdateScoreboardForGame(ctx context.Context, arg UpdateScoreboardForGameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateScoreboardForGame, arg.Member, arg.Score, arg.Game)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
