// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scoreboard.sql

package sqlc

import (
	"context"
)

const clearScoreboard = `-- name: ClearScoreboard :exec
TRUNCATE TABLE public.scoreboards
`

func (q *Queries) ClearScoreboard(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearScoreboard)
	return err
}

const getMemberGlobalScore = `-- name: GetMemberGlobalScore :one
SELECT
    DENSE_RANK() OVER (
        ORDER BY
            sum(score) DESC
    ) position,
    sum(score) score
FROM
    public.scoreboards
WHERE
    member = $1
`

type GetMemberGlobalScoreRow struct {
	Position int64
	Score    int64
}

func (q *Queries) GetMemberGlobalScore(ctx context.Context, member int64) (GetMemberGlobalScoreRow, error) {
	row := q.db.QueryRow(ctx, getMemberGlobalScore, member)
	var i GetMemberGlobalScoreRow
	err := row.Scan(&i.Position, &i.Score)
	return i, err
}

const getMemberScoreForGame = `-- name: GetMemberScoreForGame :one
SELECT
    position, score
FROM (
    SELECT
        DENSE_RANK() OVER (
            ORDER BY
                score DESC
        ) position,
        score
    FROM
        public.scoreboards
    WHERE
        game = $1
)
WHERE
    member = $2
`

type GetMemberScoreForGameParams struct {
	Game   ScoreboardGame
	Member int64
}

type GetMemberScoreForGameRow struct {
	Position int64
	Score    int16
}

func (q *Queries) GetMemberScoreForGame(ctx context.Context, arg GetMemberScoreForGameParams) (GetMemberScoreForGameRow, error) {
	row := q.db.QueryRow(ctx, getMemberScoreForGame, arg.Game, arg.Member)
	var i GetMemberScoreForGameRow
	err := row.Scan(&i.Position, &i.Score)
	return i, err
}

const getWinnerForGame = `-- name: GetWinnerForGame :many
SELECT
    position, member, score
FROM (
    SELECT
        DENSE_RANK() OVER (
            ORDER BY
                score DESC
        ) position,
        member,
        score
    FROM
        public.scoreboards
    WHERE
        game = $1
)
WHERE
    position = 1
`

type GetWinnerForGameRow struct {
	Position int64
	Member   int64
	Score    int16
}

func (q *Queries) GetWinnerForGame(ctx context.Context, game ScoreboardGame) ([]GetWinnerForGameRow, error) {
	rows, err := q.db.Query(ctx, getWinnerForGame, game)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWinnerForGameRow
	for rows.Next() {
		var i GetWinnerForGameRow
		if err := rows.Scan(&i.Position, &i.Member, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const showGlobalScoreboard = `-- name: ShowGlobalScoreboard :many
SELECT
    DENSE_RANK() OVER (
        ORDER BY
            score DESC
    ) position,
    member,
    sum(score) score
FROM
    public.scoreboards
GROUP BY
    member
`

type ShowGlobalScoreboardRow struct {
	Position int64
	Member   int64
	Score    int64
}

func (q *Queries) ShowGlobalScoreboard(ctx context.Context) ([]ShowGlobalScoreboardRow, error) {
	rows, err := q.db.Query(ctx, showGlobalScoreboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShowGlobalScoreboardRow
	for rows.Next() {
		var i ShowGlobalScoreboardRow
		if err := rows.Scan(&i.Position, &i.Member, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const showScoreboardForGame = `-- name: ShowScoreboardForGame :many
SELECT
    DENSE_RANK() OVER (
        ORDER BY
            score DESC
    ) position,
    member,
    score
FROM
    public.scoreboards
WHERE
    game = $1
`

type ShowScoreboardForGameRow struct {
	Position int64
	Member   int64
	Score    int16
}

func (q *Queries) ShowScoreboardForGame(ctx context.Context, game ScoreboardGame) ([]ShowScoreboardForGameRow, error) {
	rows, err := q.db.Query(ctx, showScoreboardForGame, game)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShowScoreboardForGameRow
	for rows.Next() {
		var i ShowScoreboardForGameRow
		if err := rows.Scan(&i.Position, &i.Member, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScoreboardForGame = `-- name: UpdateScoreboardForGame :exec
INSERT INTO
    public.scoreboards (member, score, game)
VALUES
    ($1, 1, $2) ON CONFLICT (member) DO
UPDATE
SET
    score = score + 1
`

type UpdateScoreboardForGameParams struct {
	Member int64
	Game   ScoreboardGame
}

func (q *Queries) UpdateScoreboardForGame(ctx context.Context, arg UpdateScoreboardForGameParams) error {
	_, err := q.db.Exec(ctx, updateScoreboardForGame, arg.Member, arg.Game)
	return err
}
